### ISSUE TITLE
Configure option key and label

### ISSUE THREAD

**Issue by 90arther** [riophae/vue-treeselect#1]
Hi, The document show that option must be use id and label as the key name, can i configure them?

**Comment by riophae** [comment]
No, currently there is no way to do that. Despite it's not difficult to make vue-treeselect to support that feature, I personally think it's better to use `id` and `label` as the key names in general. Because you very likely get into a state lately where you need to use other features of vue-treeselect that require you to add more properties to option objects and there will be no way to customize the key names of these properties. That is to say, eventually you may have no choice but to use `key` and `label`.

If you think there is still a need to customize the key names, feel free to leave your opinions and please describe the situation as detailed as possible.

**Comment by 90arther** [comment]
We assume out product need to adjustment for two languages. The label need to use cnName when product language is Chinese and use frenchName when product language is French.
```json
[
   {
     id: 001,
     name: 'SERVICE',
     cnName: '服务',
     frenchName: 'UN SERVICE'
   },
  {
    id: 002,
    name: 'PRODUCT',
    cnName: '产品‘,
    frenchName :'PRODUIT'
  }
]
```

**Comment by riophae** [comment]
Hummm, for this case, I think your API service should be able to determine the language to display before it sends the data. It's not necessary to determine the key at browser side.

**Comment by RinorMehmeti** [comment]
I thin it's necessary to have this feature to configure the key and label. There are cases where you are using a third party API and the key and label are different from 'id' and 'label' (usually 'label' is different), or there are cases where the team/company has a naming convention to use 'name' instead of 'label' or something else so I think it's a simple but very useful feature.

**Comment by riophae** [comment]
@90arther @RinorMehmeti Hi, sorry for it takes so long. Just to notify you that a new version including this feature is just released! Checkout the doc:  https://vue-treeselect.js.org/#customize-key-names

**Comment by 90arther** [comment]
Thanks, that's very useful.
