### ISSUE TITLE
Debugger line should not be included

### ISSUE THREAD

**Issue by DanielStout5** [riophae/vue-treeselect#157]
It seems to be poor practice to include a debugger line in an NPM package (even if it is only hit in non-production mode, it is still frustrating to have a third party package triggering my debugger)

Specifically line 11 of: https://github.com/riophae/vue-treeselect/blob/master/src/utils/warning.js

**Comment by riophae** [comment]
Actually the `debugger` was designed to be included there. It's **not** for helping myself debug, but for you. Since there are too many props, occasionally some users may misuse this component. It should not disturb you unless necessary.

I thought `debugger` could be more useful than `console.error`, as you can check the call stack and variable values, which could be useful for identifying the source of the bug sometimes. But... Now I'm re-considering about how much it actually helps.

![image](https://user-images.githubusercontent.com/1289884/44874033-715c9980-accc-11e8-95cc-63b660d60dff.png)

Thanks for feedback!
