### ISSUE TITLE
Multiple disable branch nodes unselect dont work fine

### ISSUE THREAD

**Issue by david-blanco-a** [riophae/vue-treeselect#20]
I have a problem with multiple disable branch nodes.
A three levels tree is not working fine when a item is unselected

https://codepen.io/david-blanco-a/pen/EQXNpL

How to reproduce:

1. select 'aba' (click in it)
2. select 'aaa' (click in it)
3. unselect 'aaa' (click in it)
4. select 'aaa' (click in it)
5. unselect 'aaa' (click in it)
(You can repite 2 and 3 the times you want)
6. Show the selected values, there are duplicated! ('aba')

**Comment by riophae** [comment]
Very sorry for the late reply!

The implementation of `disableBranchNodes` prop is indeed buggy. This feature is designed to be behaving like `flat`-mode, with the only difference that any branch node should always be uncheckable. As your demo shows, branch nodes are actually checkable - as far as all its descendants have been checked. This is wrong and I'm gonna have that fixed in the next release.

But... I can't get the point of the demo you provided. Can you tell more about your real world use case? Thanks.

**Comment by david-blanco-a** [comment]
With new versión (0.0.15) seems to work fine! The demo was a simple example to see the problem easily.

Thank you
