### ISSUE TITLE
Material Design style

### ISSUE THREAD

**Issue by lars-hopp** [riophae/vue-treeselect#281]
Your tree-select is very cool and the answer to a requirement I have in the application I am working on. Especially the search feature hits the sweet spot perfectly! I am using Vuetify and want to stick to the Material Design. I have several other selects in the application, and I need the tree select to exist right next to 2 other - non-tree - selects. I like the way the Material Design selects are underlined and shrink plus move the Placeholder text up to the left to act as a label once a value is selected. 
![VueTreeselect](https://user-images.githubusercontent.com/54690110/63984155-338d7f00-caa0-11e9-84c6-8a31e2ca1dc4.png)
Can you give me any guidance to help me style the tree select to look like the Material Design select of Vuetify?

Any and all help is greatly appreciated

**Comment by riophae** [comment]
I have a plan to completely redesign the styling system to make it easy to customize how the component looks. But I'm sorry, it's not finished yet. 

I suggest to copy the .less files into your project and edit them to make the component look similar to Vuetify. I know this doesn't sound good, but unfortunately, it's the only way at the moment.

Hope this helps!

**Comment by lars-hopp** [comment]
Hi. Thank you very much for your answer. I understand that this may be a major development task on your side. I will figure out a way to move forward and I wish you good luck with your - already very nice - treeview select. All the best

**Comment by frankhommers** [comment]
I have the exact same requirement @lars-hopp. So I am curious what your final solution is ;-)

**Comment by cspeer** [comment]
Wouldn't it be an easy solution for you @riophae to split your [style.less](https://github.com/riophae/vue-treeselect/blob/master/src/style.less) into 2 different files:
- variables.less
- style.less

Then when you generate the `*.css` files for distribution import both instead of one, so this won't break anyone's code that relies on the default styling. But in turn this would give anyone else the option to import both these files separately (which one would have to do anyway) and override the variables in between:

```less
@import "~@riophae/vue-treeselect/src/variables.less";
/* override some variables for example: */
@treeselect-arrow-color: #343A40;
@import "~@riophae/vue-treeselect/src/style.less";
```
