### ISSUE TITLE
Styling issue inside bootstrap table

### ISSUE THREAD

**Issue by TheAndroidGuy** [riophae/vue-treeselect#337]
Hello, thank you for this awesome component.

I am having issue with the styling of the component when it is nested inside bootstrap table.

Here is screenshot of the issue:
![example](https://user-images.githubusercontent.com/17319245/73862501-f1cae680-483e-11ea-87ee-9b7b3375b569.png)

Any idea why this is happening?

**Comment by TheAndroidGuy** [comment]
I haven't found out why this is happening and how to fix it, but i figured out different approach.
Instead of displaying the component inside the table, i used a modal window and it displays as it should.

**Comment by dadigu** [comment]
I'm having this issue as well, Not  entirely what is causing this, but I cannot move to modals, I'm building table filters where you click on a column header it will give you a dropdown with the tree select.

**Comment by dadigu** [comment]
I was having the same issue on my end, The issue in my case, where I'm using bootstrap table, the table has a css property `border-collapse: collapse;` and the tree select is inheriting that property and wil cause this issue. In order to solve this I set my tree wrapper component style to `border-collapse: separate;` (default value) and that seems to solve it.

**Comment by TheAndroidGuy** [comment]
@dadigu Thanks for posting your solution. That works for me too.
