### ISSUE TITLE
How can i define default selected item?

### ISSUE THREAD

**Issue by myagmarsurensedjav** [riophae/vue-treeselect#4]
When i need to edit some resource. the treeselect should already have selected a specific value. How can i do this?

**Comment by riophae** [comment]
Do you mean preselect values?
If you are using `v-model`, it should look like:

```html
<template>
  <treeselect :multiple="true" :options="options" v-model="value" />
</template>
```

```js
export default {
  data: {
    options: [ ... ],
    value: [ 'a', 'b' ], // preselect options with id `a` and `b`
  },
}
```

**Comment by selmonal** [comment]
It works but when i try select a new branch it doesn't load the root options only shows one.

**Comment by riophae** [comment]
Could your paste your full code here? I can't get your ideas :(

**Comment by reg2005** [comment]
Please see https://codepen.io/anon/pen/mqPBOo.

**Comment by riophae** [comment]
@reg2005 It is a known issue. However I have not figure out the proper way to handle that case... Do you have any suggestions?

I think you could try this approach: (assume a as a root option, aa as a second-level option... etc)

```html
<treeselect :load-root-options="loadRootOptions" :multiple="true" v-model="value" />
```

```js
export default {
  data: {
    value: [ 'aa', 'bb' ],
  },

  methods: {
    loadRootOptions(callback) {
      // assue the default selected options are `aa` and `bb`
      // then we need to preload these options as well as their silbing nodes & ancestor nodes
      $.post('/api/loadOptions', { ids: [ 'aa', 'bb' ] }, (data) => {
        // expect data to contain all root nodes and all sibling nodes of `aa` and `bb`
        // [ {
        //   id: 'a',
        //   label: 'a',
        //   children: [ {
        //     id: 'aa',
        //     label: 'aa',
        //   }, {
        //     id: 'ab',
        //     label: 'ab',
        //   } ],
        // }, {
        //   id: 'b',
        //   label: 'b',
        //   children: [ {
        //     id: 'ba',
        //     label: 'ba',
        //   }, {
        //     id: 'bb',
        //     label: 'bb',
        //   } ],
        // } ]
        callback(null, data)
      })
    },
  },
}
```

The key point is that you have to implement the back-end API.

**Comment by soetedja** [comment]
Thanks for the great component, but I'm facing the same issue. Any solution for this?

**Comment by hjoensson** [comment]
Really great component. I'm also facing the same problem. 

There is a value prop also that I thought could help here. But I can't get it to work.
https://riophae.github.io/vue-treeselect/#props

**Comment by ezra-obiwale** [comment]
@riophae Having the same issue.

Suggestion:

1. Let `v-model` accept an array of object with keys `id` and `label`
2. Provide another prop (a function) which is called with the provided id's but returns an array of object with keys `id` and `label`.

What do you think?

**Comment by ezra-obiwale** [comment]
Another way would be to do what [vue-multiselect](https://github.com/shentao/vue-multiselect) does:

- accept any object in the `options` array while taking props `label` and `track-by`.
- pass the full object @change
- accept an array of the object as defaults

What thinks you?

**Comment by riophae** [comment]
@ezra-obiwale Thanks for your advice! 

There are two problems with default selected options that are not loaded into the tree:

1. How to display the right labels of the default selected options in the textbox?
2. How to display the right tree?

As you suggested, let `v-model` accepts an array of object is worth considering. But it only solves the problem 1. If the default selected option is at a deep level, the tree is impossible to be rendered correctly. For example, assume we have a tree like this:

```
⯆[ ] a
  |--[ ] aa
  |--[ ] ab
⯆[ ] b
  |--[ ] ba
  |--[ ] bb
```

Assume we have the leaf node `aa` as default selected, and only the top level options are available on mount, all the second level options to be delayed loaded. The tree should be rendered like this:

```
⯈[-] a
⯈[ ] b
```

Because we don't know where the leaf node `aa` is in the tree (we have no idea about the relationship between `a` and `aa`), so we can only render the tree like this:

```
⯈[ ] a
⯈[ ] b
```

To solve the problem 2, we must load every nodes from the selected node to it's top-level ancestor.

**Comment by ezra-obiwale** [comment]
@riophae You're right, it's all better solved by [#4 (comment)](#issuecomment-341943297) but **v-model** still needs to accept an array of objects. How soon can we have that?

**Comment by riophae** [comment]
@ezra-obiwale Hi, just to notify you that vue-treeselect v0.0.13 finally supports accepting objects besides ids! For example:

```vue
<template>
  <treeselect :options="options" v-model="value" value-format="object" />
</template>

<script>
  export default {
    data() {
      return {
        options: [ ... ],
        value: {
          id: 'a',
          label: 'a',
        },
      }
    },
  }
</script>

```

There is a new prop called `valueFormat`. To keep the old behavior, its default value is `"id"`. Here we set it to `"object"` to make vue-treeselect accept objects. 

Another thing worth noting is that, it's not only you need to pass `object`/`object[]` as `value` to the component, everytime the `value` changes the component will pass you back `object`/`object[]` too (which was previours `id`/`id[]`).

**Comment by ezra-obiwale** [comment]
@riophae Great job. Thank you.

I'll definitely check it out.

Cheers

**Comment by riodw** [comment]
#### How do you use `value-format="object"` with `v-model=null` ?
_Great project BTW!_

##### Example:
```html
<treeselect
  v-model="selected_object"
  :options="array_of_objects"
  value-format="object"
/>
```
```JavaScript
selected_object: null,
```
or
```JavaScript
selected_object: "",
```
or
```JavaScript
selected_object: undefined,
```

I ask because vue used with a normal `<select>` supports object selection with `v-model` being initialized to "nothing". In order for me to use object selection here `v-model` needs to be initialized with a default object. How can I make it so `v-model` has NO default selection but still use `value-format="object"`?
