### ISSUE TITLE
Set children to null (having previously been set) the arrow remains pointing down

### ISSUE THREAD

**Issue by alexbainbridge** [riophae/vue-treeselect#97]
My use case is that the tree shows options near a certain location. When the location updates, I need to refresh the option list dynamically. I do this by setting the options children back to null when location updates.

This works and forces the tree to search again when the user interacts with the tree however you can see here, on HOTEL, that the arrow remains pointed down V (because there were children there before I set it back to null) rather than >

![arrow](https://user-images.githubusercontent.com/1144763/40497572-772aa15e-5f74-11e8-980d-b9d1950de5b7.png)

User also has to click several times - once to put the arrow back to > then a second time to make it search again (setting to V) 

**Expected behaviour**
I would expect that when options are changed dynamically that the arrow state is also rechecked to make their open / closed state to match the newly updated children status. i.e. if there WERE children and now children is null, it should go back to > rather than stay on V

**Comment by riophae** [comment]
Currently, the internal logic of vue-treeselect is that, after being set `children` as an array (whether it's empty or not), a branch node will turn to "loaded" stated, and cannot go back to "unloaded" state. That's why you cannot reset state by setting `children: null`. I'll consider changing this behavior.

As a workaround, you can add a `key` to `<treeselect />`, its value should be generated based on user entered location. For example:

```html
<div>
  Location: <input type="text" name="location" v-model="location" />
  <treeselect :key="location" ... />
</div>
```

Then every time the user enters a new location, a new instance of vue-treeselect will be created and its states will be fully reset (the user selected value will be kept).

**Comment by alexbainbridge** [comment]
Thanks for the idea! 

Yeah better if you can address your end, if possible. Thank you!
